apiVersion: apps/v1
kind: Deployment
metadata:
  name: professional-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: professional-service
  template:
    metadata:
      labels:
        app: professional-service
    spec:
      containers:
        - name: professional-service
          image: professional-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: professional-service
spec:
  selector:
    app: professional-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
    
